qcom: qpnp-pq: Fix -Wpointer-to-int-cast
drivers/power/supply/qcom/qpnp-qg.c:4741:21: error: cast to smaller integer type 'u8' (aka 'unsigned char') from 'const void *' [-Werror,-Wvoid-pointer-to-int-cast]
        chip->qg_version = (u8)of_device_get_match_data(&pdev->dev);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix `chip->qg_version = (u8)of_device_get_match_data(&pdev->dev)`
by casting pointer value to enum qg_version instead of truncated
int type.

Bug: 171827315
Signed-off-by: lucaswei <lucaswei@google.com>
Change-Id: I1dd1eb91bda9b44ca640a2c89c94d158abff5e7f
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
Signed-off-by: muralivijay <muralidharan9845@gmail.com>
Signed-off-by: chrisl7 <wandersonrodriguesf1@gmail.com>